remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme

#---------------------------------------------

theme: jekyll-theme-dinky
title: sclipscomb's homepage
description: Sam's Installation Guide for Arch Linux
