remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

#---------------------------------------------

theme: jekyll-theme-minimal
title: sclipscomb's homepage
description: Sam's Installation Guide for Arch Linux
