remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme

#---------------------------------------------

theme: jekyll-theme-tactile
title: sclipscomb's homepage
description: Sam's Installation Guide for Arch Linux
